Updated handleAuthClick to return a promise
Kubessandra/react-google-calendar-api pull request #69
Opened 2021-06-09 22:32 UTC by chantelc-mb

Updated handleAuthClick to return a promise. Hoping to close this issue: handleAuthClick should return promise #67.

2021-06-10 00:17 UTC, nickakey commented
Made this PR into your branch to update the readme for these changes :)

https://github.com/chantelc-mb/react-google-calendar-api/pull/1

2021-06-11 09:13 UTC, Kubessandra requested changes

2021-06-11 09:13 UTC, Kubessandra commented on src/ApiCalendar.ts
> +   public handleAuthClick(): any {
```suggestion
   public handleAuthClick(): Promise<any> {
```

2021-06-11 09:13 UTC, Kubessandra commented on README.md
> +    public handleAuthClick(): any
```suggestion
    public handleAuthClick(): Promise<any>
```

2021-06-11 09:13 UTC, Kubessandra commented on README.md
>            ApiCalendar.handleAuthClick();
```suggestion
          ApiCalendar.handleAuthClick()
```

2021-06-11 09:13 UTC, Kubessandra commented on README.md
> +            'sign in succesful!'
```suggestion
            console.log('sign in succesful!');
```

2021-06-11 09:13 UTC, Kubessandra commented on README.md
> +            `sign in failed ${e}`
```suggestion
            console.error(`sign in failed ${e}`);
```

2021-12-28 11:53 UTC, Kubessandra approved these changes

2022-01-09 14:45 UTC, merged