feat: create event with video conference
Kubessandra/react-google-calendar-api pull request #98
Opened 2023-02-13 09:23 UTC by OchotaDariusz

2023-02-13 20:55 UTC, OchotaDariusz commented on src/ApiCalendar.ts
> +  public createEventWithVideoConference(
Without "ts-ignore" the `conferenceData` does: `Object literal may only specify known properties, and 'conferenceData' does not exist in type 'EventInput'.` I'll merge that two methods tomorrow

2023-02-17 08:56 UTC, OchotaDariusz commented
Is there anything more you want me to change in code?

2023-02-17 14:21 UTC, Kubessandra requested changes
Just update the README, and everything good 🚀 👌

2023-02-17 14:57 UTC, Kubessandra approved these changes

2023-02-17 14:57 UTC, merged